name: deploy

on: 
  push:
    branches:
      -"main"
      
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secret.DOCKERUSER}}
        password: ${{secret.TOKEN}}
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secret.DOCKERUSER}}/nest-demo:latest
